version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    image: polianalima/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  
  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network


networks:
  node-network:
    driver: bridge
